name: Build and ping FeaturePeek
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      NEXT_PUBLIC_LM_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_API_KEY}}
      NEXT_PUBLIC_LM_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_AUTH_DOMAIN}}
      NEXT_PUBLIC_LM_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_PROJECT_ID}}
      NEXT_PUBLIC_LM_FIREBASE_DATABASE_URL: ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_DATABASE_URL}}
      NEXT_PUBLIC_LM_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_STORAGE_BUCKET}}
      NEXT_PUBLIC_LM_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_MESSAGING_SENDER_ID}}
      NEXT_PUBLIC_LM_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_APP_ID}}
      NEXT_PUBLIC_LM_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_MEASUREMENT_ID}}
    steps:
      - uses: actions/checkout@v2
      - name: Use node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install
      - name: Build NextJS -> Static
        run: yarn export
      - name: Ping FeaturePeek
        run: bash <(curl -s https://peek.run/ci)
