name: size
on: [pull_request]
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      NEXT_PUBLIC_LM_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_API_KEY}}
      NEXT_PUBLIC_LM_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_AUTH_DOMAIN}}
      NEXT_PUBLIC_LM_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_PROJECT_ID}}
      NEXT_PUBLIC_LM_FIREBASE_DATABASE_URL: ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_DATABASE_URL}}
      NEXT_PUBLIC_LM_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_STORAGE_BUCKET}}
      NEXT_PUBLIC_LM_FIREBASE_MESSAGING_SENDER_ID:  ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_MESSAGING_SENDER_ID}}
      NEXT_PUBLIC_LM_FIREBASE_APP_ID:  ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_APP_ID}}
      NEXT_PUBLIC_LM_FIREBASE_MEASUREMENT_ID:  ${{ secrets.NEXT_PUBLIC_LM_FIREBASE_MEASUREMENT_ID}}

    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
